/* C<->Python bit-exact parity test.
 *
 * Includes the committed fixture generated by kws-framework/tools/gen_parity_case.py
 * (a quantized DS-CNN + a random int8 input + the int8 logits produced by the Python
 * reference kwslib.infer_int8) and asserts the C engine reproduces them exactly.
 * This is the guarantee that the off-device training/quantization framework and the
 * on-device engine are the same numeric function.
 */
#include "core/kws_model.h"
#include "parity_model.h"
#include "parity_case.h"
#include "test.h"

static void test_parity_logits(void)
{
    const kws_model_t *m = kws_model_get();
    int8_t logits[KWS_MAX_CLASSES];

    CHECK(kws_model_infer(m, parity_input, logits));
    CHECK_EQ_INT(m->num_classes, parity_num_classes);
    CHECK_EQ_INT(m->in_h, parity_in_h);
    CHECK_EQ_INT(m->in_w, parity_in_w);

    for (int i = 0; i < parity_num_classes; i++) {
        CHECK_EQ_INT((int)logits[i], (int)parity_expected[i]);
    }
}

TEST_MAIN_BEGIN("parity")
    RUN(test_parity_logits);
TEST_MAIN_END()
