"""Codegen: quantized-model dict -> C `kws_model_data.h` for the firmware.

Emits static const weight/bias/multiplier arrays and a designated-initializer
kws_model_t plus a kws_model_get() accessor. Array flattening uses C row-major order,
matching the indexing in firmware/core/src/kws_model.c and nn/kernels.c.
"""
from __future__ import annotations

import numpy as np


def _c_array(ctype, name, values):
    vals = ", ".join(str(int(v)) for v in values)
    if not vals:
        vals = "0"
    return f"static const {ctype} {name}[] = {{ {vals} }};\n"


def generate(qm: dict, symbol: str = "g_kws_model") -> str:
    out = []
    out.append("/* Auto-generated by kwslib.codegen. Do not edit by hand. */\n")
    out.append("#ifndef KWS_MODEL_DATA_H\n#define KWS_MODEL_DATA_H\n\n")
    out.append('#include "core/kws_model.h"\n\n')

    nb = qm['n_blocks']

    out.append(_c_array("int8_t", "conv_w", qm['conv_w'].flatten()))
    out.append(_c_array("int32_t", "conv_b", qm['conv_b'].flatten()))
    out.append(_c_array("int32_t", "conv_mult", qm['conv_mult']))
    out.append(_c_array("int", "conv_shift", qm['conv_shift']))

    if nb:
        out.append(_c_array("int8_t", "dw_w", qm['dw_w'].flatten()))
        out.append(_c_array("int32_t", "dw_b", qm['dw_b'].flatten()))
        out.append(_c_array("int32_t", "dw_mult", qm['dw_mult']))
        out.append(_c_array("int", "dw_shift", qm['dw_shift']))
        out.append(_c_array("int8_t", "pw_w", qm['pw_w'].flatten()))
        out.append(_c_array("int32_t", "pw_b", qm['pw_b'].flatten()))
        out.append(_c_array("int32_t", "pw_mult", qm['pw_mult']))
        out.append(_c_array("int", "pw_shift", qm['pw_shift']))

    out.append(_c_array("int8_t", "fc_w", qm['fc_w'].flatten()))
    out.append(_c_array("int32_t", "fc_b", qm['fc_b'].flatten()))
    out.append("\n")

    def f(x):
        return f"{float(x):.8e}f"

    dw_fields = (
        "    .dw_w = dw_w, .dw_b = dw_b, .dw_mult = dw_mult, .dw_shift = dw_shift,\n"
        f"    .dw_k = {qm['dw_k']}, .dw_stride = {qm['dw_stride']}, .dw_pad = {qm['dw_pad']},\n"
        "    .pw_w = pw_w, .pw_b = pw_b, .pw_mult = pw_mult, .pw_shift = pw_shift,\n"
        f"    .pw_oc = {qm['pw_oc']},\n"
        if nb else
        "    .dw_w = 0, .dw_b = 0, .dw_mult = 0, .dw_shift = 0,\n"
        f"    .dw_k = 0, .dw_stride = 1, .dw_pad = 0,\n"
        "    .pw_w = 0, .pw_b = 0, .pw_mult = 0, .pw_shift = 0,\n"
        f"    .pw_oc = {qm['pw_oc']},\n"
    )

    out.append(f"static const kws_model_t {symbol} = {{\n")
    out.append(f"    .in_h = {qm['in_h']}, .in_w = {qm['in_w']},\n")
    out.append("    .conv_w = conv_w, .conv_b = conv_b, "
               ".conv_mult = conv_mult, .conv_shift = conv_shift,\n")
    out.append(f"    .conv_oc = {qm['conv_oc']}, .conv_kh = {qm['conv_kh']}, "
               f".conv_kw = {qm['conv_kw']}, .conv_stride = {qm['conv_stride']}, "
               f".conv_pad = {qm['conv_pad']},\n")
    out.append(f"    .n_blocks = {nb},\n")
    out.append(dw_fields)
    out.append(f"    .gap_mult = {qm['gap_mult']}, .gap_shift = {qm['gap_shift']},\n")
    out.append("    .fc_w = fc_w, .fc_b = fc_b, "
               f".fc_mult = {qm['fc_mult']}, .fc_shift = {qm['fc_shift']}, "
               f".num_classes = {qm['num_classes']},\n")
    out.append(f"    .in_zp = {qm['in_zp']}, .conv_zp = {qm['conv_zp']}, "
               f".dw_zp = {qm['dw_zp']}, .pw_zp = {qm['pw_zp']},\n")
    out.append(f"    .gap_zp = {qm['gap_zp']}, .out_zp = {qm['out_zp']},\n")
    out.append(f"    .out_scale = {f(qm['out_scale'])}, "
               f".wake_class = {qm['wake_class']}, .threshold = {f(qm['threshold'])},\n")
    out.append("};\n\n")
    out.append(f"static inline const kws_model_t *kws_model_get(void) {{ return &{symbol}; }}\n")
    out.append("\n#endif /* KWS_MODEL_DATA_H */\n")
    return "".join(out)


def write_header(path: str, qm: dict, symbol: str = "g_kws_model"):
    with open(path, "w") as fh:
        fh.write(generate(qm, symbol))
