/* Auto-generated by kwslib.codegen. Do not edit by hand. */
#ifndef KWS_MODEL_DATA_H
#define KWS_MODEL_DATA_H

#include "core/kws_model.h"

static const int8_t conv_w[] = { -31, -43, -22, 15, -17, 32, 106, 127, 85, -52, 11, -13, -127, -61, -45, -111, -10, -11, 32, 67, 17, 118, 22, 67, 127, 94, 51, -97, -30, 41, -127, 1, 8, 6, 45, 76, -21, 14, 69, 79, -127, 80, 69, 28, -15, 5, 79, 97, 127, 102, 64, -38, -1, 25 };
static const int32_t conv_b[] = { -1193, -2672, -2340, 2549, -1971, 1257 };
static const int32_t conv_mult[] = { 1092701854, 2116507670, 1453416777, 1370092416, 2121378855, 1947484013 };
static const int conv_shift[] = { -7, -9, -8, -9, -9, -8 };
static const int8_t dw_w[] = { 15, -99, 120, -102, -78, 1, -41, 102, 52, -60, -57, -110, -127, 0, 53, 71, -99, 49, 25, 74, -28, -77, -21, 127, 35, -93, -60, -115, 6, 126, 30, -127, 22, -116, -127, 104, -77, -16, 28, -24, -57, 61, 93, -100, 127, 16, 42, 117, 99, 19, 48, -127, -65, 5 };
static const int32_t dw_b[] = { 798, -858, -953, -449, -936, 450 };
static const int32_t dw_mult[] = { 1707402155, 1899989118, 1541236890, 1083608414, 1331273146, 1217675296 };
static const int dw_shift[] = { -8, -9, -8, -8, -9, -8 };
static const int8_t pw_w[] = { -127, -11, -59, -105, -105, -4, -21, 90, 30, 70, 97, 127, -127, 53, 48, 27, 28, 15, 56, 7, -127, -13, -18, 82, -39, -15, -76, -36, 24, -127, 127, -6, 40, -98, 32, -52 };
static const int32_t pw_b[] = { -234, -364, 62, 391, -91, -124 };
static const int32_t pw_mult[] = { 1191532498, 1878433933, 1124766727, 1917606960, 1226341145, 1924806739 };
static const int pw_shift[] = { -6, -7, -5, -6, -6, -6 };
static const int8_t fc_w[] = { -44, 1, -16, 59, -25, -96, -4, -38, 60, -16, 20, 70, 40, 60, 40, -127, -10, -34 };
static const int32_t fc_b[] = { 330, 300, -572 };

static const kws_model_t g_kws_model = {
    .in_h = 8, .in_w = 8,
    .conv_w = conv_w, .conv_b = conv_b, .conv_mult = conv_mult, .conv_shift = conv_shift,
    .conv_oc = 6, .conv_kh = 3, .conv_kw = 3, .conv_stride = 1, .conv_pad = 1,
    .n_blocks = 1,
    .dw_w = dw_w, .dw_b = dw_b, .dw_mult = dw_mult, .dw_shift = dw_shift,
    .dw_k = 3, .dw_stride = 1, .dw_pad = 1,
    .pw_w = pw_w, .pw_b = pw_b, .pw_mult = pw_mult, .pw_shift = pw_shift,
    .pw_oc = 6,
    .gap_mult = 1391832646, .gap_shift = -4,
    .fc_w = fc_w, .fc_b = fc_b, .fc_mult = 1540872881, .fc_shift = -6, .num_classes = 3,
    .in_zp = -56, .conv_zp = -128, .dw_zp = -128, .pw_zp = -128,
    .gap_zp = -128, .out_zp = -24,
    .in_scale = 1.62626911e-02f,
    .out_scale = 1.07191460e-01f, .wake_class = 1, .threshold = 5.00000000e-01f,
};

static inline const kws_model_t *kws_model_get(void) { return &g_kws_model; }

#endif /* KWS_MODEL_DATA_H */
