#!/usr/bin/env python3
"""Generate the C<->Python parity fixture.

Builds a deterministic DS-CNN, quantizes it through the real pipeline, runs the Python
int8 reference on a fixed random int8 input, and emits:
  tests/host/generated/parity_model.h   (codegen'd kws_model_t, symbol g_parity_model)
  tests/host/generated/parity_case.h    (input + expected int8 logits)

The committed fixtures let tests/host/test_parity.c assert the C engine reproduces the
Python reference bit-for-bit, with no Python needed at C build time. Re-running this must
be byte-identical (checked by tests/py/test_parity_regen.py).
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.dirname(HERE))  # kws-framework/

from kwslib import model as kmodel, quantize, codegen, infer_int8, dataset  # noqa: E402

SEED = 1234
IN_H, IN_W = 8, 8
NUM_CLASSES = 3


def build():
    m = kmodel.DSCNN(IN_H, IN_W, conv_oc=4, conv_k=3, n_blocks=1,
                     pw_oc=4, num_classes=NUM_CLASSES, seed=SEED)
    X, _ = dataset.make_synthetic(6, IN_H, IN_W, NUM_CLASSES, seed=SEED)
    qm = quantize.build_quant_model(m, X, wake_class=1, threshold=0.5)

    rng = np.random.default_rng(SEED + 1)
    inp = rng.integers(-128, 128, size=IN_H * IN_W).astype(np.int8)
    expected = infer_int8.infer(qm, inp)
    return qm, inp, expected


def emit(qm, inp, expected, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    codegen.write_header(os.path.join(out_dir, "parity_model.h"), qm,
                         symbol="g_parity_model")

    inp_vals = ", ".join(str(int(v)) for v in inp)
    exp_vals = ", ".join(str(int(v)) for v in expected)
    case = (
        "/* Auto-generated by gen_parity_case.py. Do not edit by hand. */\n"
        "#ifndef PARITY_CASE_H\n#define PARITY_CASE_H\n\n"
        "#include <stdint.h>\n\n"
        f"static const int parity_in_h = {IN_H};\n"
        f"static const int parity_in_w = {IN_W};\n"
        f"static const int parity_num_classes = {NUM_CLASSES};\n"
        f"static const int8_t parity_input[] = {{ {inp_vals} }};\n"
        f"static const int8_t parity_expected[] = {{ {exp_vals} }};\n\n"
        "#endif /* PARITY_CASE_H */\n"
    )
    with open(os.path.join(out_dir, "parity_case.h"), "w") as fh:
        fh.write(case)


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else \
        os.path.join(ROOT, "tests", "host", "generated")
    qm, inp, expected = build()
    emit(qm, inp, expected, out_dir)
    print(f"wrote parity fixture to {out_dir}: expected logits = {list(map(int, expected))}")


if __name__ == "__main__":
    main()
